name: mathgaps_movie_site
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  extended_image:
    git:
      url: https://github.com/oliatienza/extended_image.git
      ref: dev
  auto_route: ^0.6.9
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  dio_log: ^1.3.5
  flutter_fadein: ^2.0.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  glassmorphism: ^2.0.1
  google_fonts: ^1.1.2
  infinite_widgets: ^2.0.0
  injectable: ^1.0.5
  json_annotation: ^3.1.1
  pretty_dio_logger: ^1.1.1
  responsive_builder: ^0.4.1
  retrofit: ^1.3.4+1
  stacked: ^1.7.7
  supercharged: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: null
  freezed: ^0.12.7
  hive_generator: ^0.8.2
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.1
  lint: ^1.0.0
  retrofit_generator: ^1.4.0+2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/png/
